### ISSUE TITLE
high performing cache services: Screenshot for 5005 and 8080 incorrect after initial deploy of inventory services

### ISSUE THREAD

**Issue by gbengataylor** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m4-guides#29]
change to 

![image](https://user-images.githubusercontent.com/30447678/113795552-3429d500-971b-11eb-8850-751937b33560.png)

Then select

![image](https://user-images.githubusercontent.com/30447678/113795615-528fd080-971b-11eb-85aa-6e27014dbd5f.png)

**Comment by danieloh30** [comment]
Can you also create a PR for this?

**Comment by gbengataylor** [comment]
will do!

**Comment by danieloh30** [comment]
PR is merged
