### ISSUE TITLE
Namespace changes after disconnect

### ISSUE THREAD

**Issue by patman312** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m4-guides#32]
In chapter 3.1 (Deploying Inventory Service) the following terminal-commands are provided:

> oc project user9-cloudnativeapps && \
> mvn clean compile package -DskipTests -f $CHE_PROJECTS_ROOT/cloud-native-workshop-v2m4-labs/inventory-service

In the following chapters only the Maven-command is provided. If an error or disconnect occurs, the namespace automatically changes. To work around that, my proposition is to provide the command

> oc project user9-cloudnativeapps && \

also before every following deployment-command - although it's redundant - to always be sure to work in the correct namespace.

**Comment by danieloh30** [comment]
Thanks for the suggestion. It seems too redundant and in module 4, devs need to deploy all services to one namespace, `userXX-cloudnativeapps` except for the OpenShift pipeline example. So I'd say if there's unexpected disconnected error, devs just need to change the namespace(project) via oc command once.

**Comment by nexus-Six** [comment]
Hi Daniel. I just ran this workshop and due to an (AWS networking) outage and subsequent workspace restarts almost all of the attendees ran into this issue.  How about adding a hint to always make sure to be in the right namespace  ( oc project ...) for subsequent commands, especially when reconnecting to OCP? https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m4-guides/blob/b48445a97dde5f81a2c8ed8e121b9e5f9e19eb3d/high-performing-cache-services.adoc?plain=1#L247

**Comment by danieloh30** [comment]
Wondering if all attendees have had no experience using OpenShift before? Also, to be clear, once you had the network failure, which project did you stay in automatically? (e.g. `userxx-cloudnative-pipeline`). I'm trying to understand how the network failure changed the user's project. What was the flow you actually did after the network failure? I honestly never heard this issue before.

**Comment by nexus-Six** [comment]
They have ocp experience but especially if you are only running module 4 the "oc project"-command is a bit hidden in the concatenated commands and the reason for the other namespaces is unknown. After restarting the workspaces (which is sometime necessary) and running openshift login again you always end up in "userxx-catalog". Then participants continue with the commands where they left off for some time until they realize that something is off.  I know it is a bit of an edge case but I can see others stumbling over this was well and a hint might alleviate this potential pitfall.

**Comment by danieloh30** [comment]
that's what I'm confused. M4 only created userxx-cloudnativeapps and userxx-cloudnative-pipeline. So if a user logs in to openshift, the default project should be userxx-cloudnativeapps. are you sure if you ran m4?

**Comment by nexus-Six** [comment]
Ok, I see what happened here. I deployed all 4 modules but only ran module 4 with the group.  So I guess this moves the issue even more to the edge.

**Comment by danieloh30** [comment]
yeah, that's what I thought. I'll monitor if a similar issue happens again in the future. In the meantime, let's let the instructor handle this rather than adding unnecessary notes :) Thanks for bringing this to my attention.
