### ISSUE TITLE
[evolve-serverless-services.adoc] link is broken.(404)

### ISSUE THREAD

**Issue by ssetoredhat** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m4-guides#34]
> In the lab, OpenShift Serverless Operator is already installed on your OpenShift 4 cluster but if you want to install it on your own OpenShift cluster, follow [Installing OpenShift Serverless](https://docs.openshift.com/container-platform/latest/serverless/installing_serverless/installing-openshift-serverless.html).

maybe 
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/serverless/install#install-serverless-operator

branch: ocp-4.10, ocp-4.9

**Comment by danieloh30** [comment]
Good catch! Just fixed. FYI, you need to kill the guides-m4-xxx pod in the labs-infra project if you need to pull the latest guide in the running cluster.

**Comment by ssetoredhat** [comment]
Thanks!
I wish I had known that a week ago. 😂
